### ISSUE TITLE
ios missing main.jsbundle

### ISSUE THREAD

**Issue by asharijuang** [qiscus/qiscus-rn-example#12]
step :

1. npm install
2. cd /ios
3. pod install
4. open qiscusrn.xcworkspace
5. run on device

can run on device but no bundle URL present.
![img_2007](https://user-images.githubusercontent.com/3271668/38911933-b2bdadfe-42fc-11e8-90ea-83a6e983de13.PNG)

**Comment by benyliantriana** [comment]
error dari react native,
ref: 
https://medium.com/@andrewcbancroft/solving-react-natives-no-bundle-url-present-error-in-ios-9d94deb2da08
atau:
https://github.com/facebook/react-native/issues/12754

**Comment by sunupf** [comment]
ini kalau error dari react ku close aja ya
